### ISSUE TITLE
Very Low Priority Suggestion

### ISSUE THREAD

**Issue by AlphaQuata** [RayDeeUx/menuloop_randomizer#16]
Ok so this is just a quality of life suggestion that I thought of that'd be cool to add if you had like literally nothing else to do right now. You know when you're just chillin in gd and listening to the menu loops and then one comes on and you're like "this is complete trash"? Well, I think it would be cool to add a feature where you can just straight up delete the current song from your device so you never have to hear it again. (or maybe at least just blacklist it from the menuloop mod so it never plays it again if thats easier to code)

**Comment by RayDeeUx** [comment]
that... *doesn't* sound too hard, but it could be prone to crashes. i'll look into it eventually. no solid due dates tho

**Comment by AlphaQuata** [comment]
sounds good 👍

**Comment by RayDeeUx** [comment]
acknowledged on discord, should be fixed in v1.6.0
