### ISSUE TITLE
The menu music option is not respecting the music itself when "enabled and disabled again"

### ISSUE THREAD

**Issue by freakingdan** [RayDeeUx/menuloop_randomizer#17]
https://github.com/user-attachments/assets/14b82a8e-18d8-4e0d-9fb4-302e75bdc793

Can you please explain it to me why...
as the video and the title states, the menu music option is not respecting with the music itself to temporarily disable the music when using the _playlist mode_...
i just tested it.
could you please look into it and find a fix for it

**Comment by RayDeeUx** [comment]
acknowledged on discord, should be fixed in v1.6.0

**Comment by freakingdan** [comment]
hey! thanks man!
